package br.ufv.caf.votacaoeletronica.view;

import br.ufv.caf.votacaoeletronica.control.ApuracaoControl;
import br.ufv.caf.votacaoeletronica.control.CandidatoControl;
import br.ufv.caf.votacaoeletronica.control.EleitorControl;
import br.ufv.caf.votacaoeletronica.control.MesarioControl;
import br.ufv.caf.votacaoeletronica.control.VotacaoControl;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriano Marques Martins 02640
 */
public class CadastrarUrna extends javax.swing.JFrame {

    private ApuracaoControl apuracaoC;
    private VotacaoControl votacaoC;
    private CandidatoControl candidatoC;
    private EleitorControl eleitorC;
    private MesarioControl mesarioC;
    private ImageIcon icone;

    /**
     * Creates new form CadastrarUrna
     */
    public CadastrarUrna() throws IOException {
        apuracaoC = new ApuracaoControl();
        votacaoC = new VotacaoControl();
        candidatoC = new CandidatoControl();
        eleitorC = new EleitorControl();
        votacaoC.iniciarVotacao();
        //Código acessado em: http://www.larback.com.br/aula/91/Alterando-o-%C3%ADcone-da-janela-em-java
        URL url = getClass().getResource("../image/icone.png");
        Image icone = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(icone);
        this.setSize(200, 200);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        textFieldZona = new java.awt.TextField();
        label2 = new java.awt.Label();
        textFieldSecao = new java.awt.TextField();
        label3 = new java.awt.Label();
        buttonCadastrar = new java.awt.Button();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Urna");
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));

        label1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label1.setText("ZONA :");

        textFieldZona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldZona.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textFieldZona.setPreferredSize(new java.awt.Dimension(100, 20));
        textFieldZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldZonaActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label2.setText("SEÇÃO");

        textFieldSecao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textFieldSecao.setPreferredSize(new java.awt.Dimension(100, 20));
        textFieldSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSecaoActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label3.setText("CADASTRAR URNA");

        buttonCadastrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonCadastrar.setLabel("Cadastrar");
        buttonCadastrar.setPreferredSize(new java.awt.Dimension(70, 40));
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufv/caf/votacaoeletronica/image/braso.png"))); // NOI18N
        jButton1.setText("JUSTIÇA ELEITORAL");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textFieldSecao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldZona, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldSecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSecaoActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        try {
            String zona = textFieldZona.getText();
            String secao = textFieldSecao.getText();
            if (zona.contains("^[a-Z]") || secao.contains("^[a-Z]")) {
                throw new Exception("Entrada(s) inválida(s)!");
            } else {
                int iZona = Integer.parseInt(zona);
                int iSecao = Integer.parseInt(secao);
                if (iZona < 100 || iZona >= 1000 || iSecao < 0) {
                    throw new Exception("Entrada(s) inválida(s)!");
                } else {
                    mesarioC = new MesarioControl(iZona, iSecao);
                    MenuMesario mM = new MenuMesario(apuracaoC, votacaoC, candidatoC, eleitorC, mesarioC);
                    this.setVisible(false);
                    mM.setVisible(true);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        textFieldZona.setText("");
        textFieldZona.setText("");
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void textFieldZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldZonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CadastrarUrna().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(CadastrarUrna.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonCadastrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textFieldSecao;
    private java.awt.TextField textFieldZona;
    // End of variables declaration//GEN-END:variables
}
